// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/containers": {
            "get": {
                "description": "Возвращает все доступные контейнеры с опциональной фильтрацией по типу",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Получить все контейнеры",
                "parameters": [
                    {
                        "type": "string",
                        "description": "тип контейнера для фильтрации",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemes.GetAllContainersResponse"
                        }
                    }
                }
            }
        },
        "/api/containers/{container_id}": {
            "get": {
                "description": "Возвращает более подробную информацию об одном контейнере",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Получить один контейнер",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id контейнера",
                        "name": "container_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ds.Container"
                        }
                    }
                }
            },
            "put": {
                "description": "Изменить данные полей о контейнере",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Изменить котейнер",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор контейнера",
                        "name": "container_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Маркировка",
                        "name": "marking",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Тип",
                        "name": "type",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Длина",
                        "name": "length",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Высота",
                        "name": "height",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Ширина",
                        "name": "width",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Изображение контейнера",
                        "name": "image",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Груз",
                        "name": "cargo",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Вес",
                        "name": "weight",
                        "in": "formData"
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "Добавить новый контейнер",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Добавить контейнер",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Изображение контейнера",
                        "name": "image",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Маркировка",
                        "name": "marking",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Тип",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Длина",
                        "name": "length",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Высота",
                        "name": "height",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Ширина",
                        "name": "width",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Груз",
                        "name": "cargo",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Вес",
                        "name": "weight",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "Удаляет контейнер по id",
                "tags": [
                    "containers"
                ],
                "summary": "Удалить контейнер",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id контейнера",
                        "name": "container_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/containers/{container_id}/add_to_transportation": {
            "post": {
                "description": "Добавить выбранный контейнер в черновик перевозки",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Добавить в перевозку",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id контейнера",
                        "name": "container_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ds.Container"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login/": {
            "post": {
                "description": "Авторизует пользователя по логиню, паролю и отдаёт jwt токен для дальнейших запросов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Авторизация",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User login",
                        "name": "login",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemes.SwaggerLoginResp"
                        }
                    }
                }
            }
        },
        "/auth/loguot/": {
            "post": {
                "description": "Выход из аккаунта",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выйти из аккаунта",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/auth/sign_up/": {
            "post": {
                "description": "Регистрация нового пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User login",
                        "name": "login",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemes.RegisterResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ds.Container": {
            "type": "object",
            "required": [
                "cargo",
                "height",
                "length",
                "marking",
                "type",
                "weight",
                "width"
            ],
            "properties": {
                "cargo": {
                    "type": "string",
                    "maxLength": 50
                },
                "height": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "length": {
                    "type": "integer"
                },
                "marking": {
                    "type": "string",
                    "maxLength": 11
                },
                "type": {
                    "type": "string",
                    "maxLength": 50
                },
                "uuid": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "schemes.GetAllContainersResponse": {
            "type": "object",
            "properties": {
                "containers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ds.Container"
                    }
                },
                "draft_transportation": {
                    "$ref": "#/definitions/schemes.TransportationShort"
                }
            }
        },
        "schemes.RegisterResp": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "schemes.SwaggerLoginResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "schemes.TransportationShort": {
            "type": "object",
            "properties": {
                "container_count": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Container loginstics",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
